package com.simplesys.js.com.simplesys.SmartClient.System

import com.simplesys.SmartClient.System._


object Common {
    val iconAdd = "Add_Column.png"
    val iconNew = "Actions-insert-link-icon.png"
    val iconFolder = "folder.png"
    val iconFile = "file.png"
    val iconRefresh = "Refresh.png"
    val iconTreeNode = "tree_node.png"
    val iconEllipsis = "ellipsis.png"
    val iconFunctions = "function-selection.png"
    val iconStatistiq = "global_manager.png"
    val iconEdit = "edit.png"
    val delete_Column = "Delete_Column.png"
    val Delete_icon = "Delete-icon.png"
    val iconSave = "Save-icon.png"
    val iconDiscard = "cancel-icon.png"
    val iconOpenFolder = "openFolder.png"
    val iconUnknown = "unknown.png"
    val iconStatistic = "systemservice_SeqGenerator.png"
    val iconConstructor = "Start-Menu-icon.png"
    val iconControl = "ControlReading.png"
    val structure = "structure.png"
    val Actions_insert_link_icon = "Actions-insert-link-icon.png"
    val node = "node.png"
    val admin_User = "admin_User.png"
    val data = "data.png"
    val Help_icon = "Help-icon.png"
    val login = "login.png"
    val tools = "tools.png"
    val insert = "insert.png"
    val Workflow = "Workflow.png"
    val properties = "properties.png"
    val gradient = "gpadient.png"
    val copy = "copy.png"
    val send = "send.png"
    val exportDB = "exportDB.png"
    val systemservice = "systemservice.png"
    val accounts = "accounts.png"
    val export = "export.png"
    val ellipsis = "ellipsis.png"
    val font = "font.png"
    val shadow = "shadow.png"
    val info = "info.png"
}
