package com.simplesys.System.Types

import scala.language.implicitConversions

object FormItemType extends Enumeration {
    type FormItemType = Value
    val text, boolean, integer, float, date, time, enum, sequence, link, image, imageFile, binary, clob_SimpleType, dDate_SimpleType, dDateOptTime_SimpleType, dDateTime_SimpleType, dTimestamp_SimpleType, dTimestampWithTZ_SimpleType, di_SimpleType, fDouble_SimpleType, fPrice_SimpleType, fSum_SimpleType, id_SimpleType, nInt_SimpleType, sAddress_SimpleType, sBarCode_SimpleType, sCaption_SimpleType, sCode_SimpleType, sDescription_SimpleType, sEMail_SimpleType, sPasswordHashSHA_SimpleType, sPasswordPlain_SimpleType, sPhone_SimpleType, sPostalIndex_SimpleType, sURL_SimpleType, sURLDomain_SimpleType, sURLImage_SimpleType, ss_SimpleType, bBoolean_SimpleType, blob_SimpleType = Value
}

object FormItemComponentType extends Enumeration {
    type FormItemComponentType = Value
    val AutoFitTextAreaItem,
    BlurbItem,
    BooleanItem,
    ButtonItem,
    CancelItem,
    CanvasItem,
    CheckboxItem,
    ColorItem,
    ColorPickerItem,
    ComboBoxItem,
    CycleItem,
    DataPathItem,
    DateItem,
    DateRangeItem,
    DateTimeItem,
    DoubleItem,
    FileItem,
    FloatItem,
    FormItem,
    HeaderItem,
    HiddenItem,
    IntegerItem,
    IPickTreeItem,
    LinkItem,
    MiniDateRangeItem,
    MultiComboBoxItem,
    MultiFileItem,
    NativeCheckboxItem,
    PasswordItem,
    PickList,
    PickListMenu,
    PickTreeItem,
    PresetCriteriaItem,
    PresetDateRangeItem,
    RadioGroupItem,
    RelationItem,
    RelativeDateItem,
    ResetItem,
    RichTextItem,
    RowSpacerItem,
    ScrollingMenu,
    SectionItem,
    SelectItem,
    SelectOtherItem,
    SliderItem,
    SpacerItem,
    SpinnerItem,
    StaticTextItem,
    SubmitItem,
    TextAreaItem,
    TextItem,
    TimeItem,
    TimerItem,
    ToolbarItem,
    UploadItem,
    ComboboxItemWithButtons,
    FormItemWithButton,
    ComboboxItemWithClearButton,
    SkinBoxItem,
    LookupListGridEditorItem,
    ViewFileItem = Value
}
