package com.simplesys.SmartClient.DataBinding.props.dataSource

import com.simplesys.SmartClient.Forms.FormsItems.FormItem
import com.simplesys.SmartClient.Forms.Validator
import com.simplesys.SmartClient.System.Types
import com.simplesys.SmartClient.System.Types.{ValueMap, VelocityExpression, XPathExpression}
import com.simplesys.System.Types.DateDisplayFormat.DateDisplayFormat
import com.simplesys.System.Types.FieldImportStrategy.FieldImportStrategy
import com.simplesys.System.Types.HashAlgorithm.HashAlgorithm
import com.simplesys.System.Types.JoinType.JoinType
import com.simplesys.System.Types.MultipleFieldStorage.MultipleFieldStorage
import com.simplesys.System.Types.OperatorId.OperatorId
import com.simplesys.System.Types.SummaryFunction.SummaryFunction
import com.simplesys.System.Types.TimeDisplayFormat.TimeDisplayFormat
import com.simplesys.System.Types.{FormatString, HTMLString, ID}
import com.simplesys.option.IntString

import scala.scalajs.js
import scala.scalajs.js._
import scala.scalajs.js.annotation.JSName

@js.native
@JSName("DataSourceField")
class DataSourceFieldProps extends Types.Object {
    var allowClientRequestedSummaries: Boolean = js.native
    var audit: Boolean = js.native
    var autoGenerated: Boolean = js.native
    var autoQuoteCustomExpressions: Boolean = js.native
    var canEdit: Boolean = js.native
    var canExport: Boolean = js.native
    var canFilter: Boolean = js.native
    var canSave: Boolean = js.native
    var canSortClientOnly: Boolean = js.native
    var canView: Boolean = js.native
    var childrenProperty: Boolean = js.native
    var childTagName: String = js.native
    var columnCode: String = js.native
    var creatorOverrides: Boolean = js.native
    var customCriteriaExpression: String = js.native
    var customInsertExpression: String = js.native
    var customSelectExpression: String = js.native
    var customSQL: Boolean = js.native
    var customUpdateExpression: String = js.native
    var dateFormatter: DateDisplayFormat = js.native
    var decimalPad: Int = js.native
    var decimalPrecision: Int = js.native
    var deepCloneOnEdit: Boolean = js.native
    var detail: Boolean = js.native
    var displayField: Boolean = js.native
    var editorType: FormItem = js.native
    var editRequires: VelocityExpression = js.native
    var editRequiresAuthentication: Boolean = js.native
    var editRequiresRole: String = js.native
    var emptyDisplayValue: HTMLString = js.native
    var encodeInResponse: Boolean = js.native
    var escapeHTML: Boolean = js.native
    var exportFormat: FormatString = js.native
    var exportTitle: String = js.native
    var filterEditorType: FormItem = js.native
    var fkColumnCode: String = js.native
    var fkTableCode: String = js.native
    var foreignDisplayField: String = js.native
    var foreignKey: String = js.native
    var format: FormatString = js.native
    var group: String = js.native
    var hidden: Boolean = js.native
    var ignore: Boolean = js.native
    var ignoreTextMatchStyle: Boolean = js.native
    var imageHeight: Int | String = js.native
    var imageSize: Int | String = js.native
    var imageWidth: Int | String = js.native
    var implicitSequence: Boolean = js.native
    var importStrategy: FieldImportStrategy = js.native
    var inapplicable: Boolean = js.native
    var includeFrom: String = js.native
    var includeSummaryFunction: SummaryFunction = js.native
    var includeVia: String = js.native
    var initRequires: VelocityExpression = js.native
    var initRequiresAuthentication: Boolean = js.native
    var initRequiresRole: String = js.native
    var javaClass: String = js.native
    var javaCollectionClass: String = js.native
    var javaKeyClass: String = js.native
    var joinType: JoinType = js.native
    var length: Int = js.native
    var lenientXPath: Boolean = js.native
    var maxFileSize: Int = js.native
    var mimeType: String = js.native
    var multiple: Boolean = js.native
    var multipleStorage: MultipleFieldStorage = js.native
    var multipleStorageSeparator: Boolean = js.native
    var multipleValueSeparator: Boolean = js.native
    var name: ID = js.native
    var nativeName: String = js.native
    var nillable: Boolean = js.native
    var nullReplacementValue: js.Any = js.native
    var precision: js.Any = js.native
    var primaryKey: Boolean = js.native
    var propertiesOnly: Boolean = js.native
    var readOnlyEditorType: FormItem = js.native
    var relatedTableAlias: String = js.native
    var required: Boolean = js.native
    var rootValue: js.Any = js.native
    var sequenceName: String = js.native
    var showFileInline: Boolean = js.native
    var sortByField: String = js.native
    var sqlDateFormat: String = js.native
    var sqlFalseValue: String = js.native
    var sqlStorageStrategy: String = js.native
    var sqlTrueValue: String = js.native
    var storeMilliseconds: Boolean = js.native
    var storeWithHash: HashAlgorithm = js.native
    var stringInBrowser: Boolean = js.native
    var summaryFunction: SummaryFunction = js.native
    var summaryValueTitle: String = js.native
    var tableName: String = js.native
    var timeFormatter: TimeDisplayFormat = js.native
    var title: String = js.native
    var updateRequires: VelocityExpression = js.native
    var updateRequiresAuthentication: Boolean = js.native
    var updateRequiresRole: String = js.native
    var uploadFieldName: String = js.native
    var validators: Array[Validator] = js.native
    var validOperators: Array[OperatorId] = js.native
    var valueMap: ValueMap = js.native
    var valueMapEnum: String = js.native
    var valueWriteXPath: XPathExpression = js.native
    var valueXPath: XPathExpression = js.native
    var viewRequires: VelocityExpression = js.native
    var viewRequiresAuthentication: Boolean = js.native
    var viewRequiresRole: String = js.native
    var xmlAttribute: Boolean = js.native
}
