package com.simplesys.SmartClient.DataBinding.props.dataSource

import com.simplesys.SmartClient.Forms.FormsItems.FormItem
import com.simplesys.SmartClient.Forms.Validator
import com.simplesys.SmartClient.System.Types
import com.simplesys.SmartClient.System.Types.{ValueMap, VelocityExpression, XPathExpression}
import com.simplesys.System.Types.DateDisplayFormat.DateDisplayFormat
import com.simplesys.System.Types.FieldImportStrategy.FieldImportStrategy
import com.simplesys.System.Types.HashAlgorithm.HashAlgorithm
import com.simplesys.System.Types.JoinType.JoinType
import com.simplesys.System.Types.MultipleFieldStorage.MultipleFieldStorage
import com.simplesys.System.Types.OperatorId.OperatorId
import com.simplesys.System.Types.SummaryFunction.SummaryFunction
import com.simplesys.System.Types.TimeDisplayFormat.TimeDisplayFormat
import com.simplesys.System.Types.{FormatString, HTMLString, ID}
import com.simplesys.option.IntString

import scala.scalajs.js
import scala.scalajs.js._
import scala.scalajs.js.annotation.ScalaJSDefined

@ScalaJSDefined
class DataSourceFieldProps extends Types.Object {
    var allowClientRequestedSummaries: Option[Boolean] = None
    var audit: Option[Boolean] = None
    var autoGenerated: Option[Boolean] = None
    var autoQuoteCustomExpressions: Option[Boolean] = None
    var canEdit: Option[Boolean] = None
    var canExport: Option[Boolean] = None
    var canFilter: Option[Boolean] = None
    var canSave: Option[Boolean] = None
    var canSortClientOnly: Option[Boolean] = None
    var canView: Option[Boolean] = None
    var childrenProperty: Option[Boolean] = None
    var childTagName: Option[String] = None
    var columnCode: Option[String] = None
    var creatorOverrides: Option[Boolean] = None
    var customCriteriaExpression: Option[String] = None
    var customInsertExpression: Option[String] = None
    var customSelectExpression: Option[String] = None
    var customSQL: Option[Boolean] = None
    var customUpdateExpression: Option[String] = None
    var dateFormatter: Option[DateDisplayFormat] = None
    var decimalPad: Option[Int] = None
    var decimalPrecision: Option[Int] = None
    var deepCloneOnEdit: Option[Boolean] = None
    var detail: Option[Boolean] = None
    var displayField: Option[Boolean] = None
    var editorType: Option[FormItem] = None
    var editRequires: Option[VelocityExpression] = None
    var editRequiresAuthentication: Option[Boolean] = None
    var editRequiresRole: Option[String] = None
    var emptyDisplayValue: Option[HTMLString] = None
    var encodeInResponse: Option[Boolean] = None
    var escapeHTML: Option[Boolean] = None
    var exportFormat: Option[FormatString] = None
    var exportTitle: Option[String] = None
    var filterEditorType: Option[FormItem] = None
    var fkColumnCode: Option[String] = None
    var fkTableCode: Option[String] = None
    var foreignDisplayField: Option[String] = None
    var foreignKey: Option[String] = None
    var format: Option[FormatString] = None
    var group: Option[String] = None
    var hidden: Option[Boolean] = None
    var ignore: Option[Boolean] = None
    var ignoreTextMatchStyle: Option[Boolean] = None
    var imageHeight: Option[IntString[Int, String]] = None
    var imageSize: Option[IntString[Int, String]] = None
    var imageWidth: Option[IntString[Int, String]] = None
    var implicitSequence: Option[Boolean] = None
    var importStrategy: Option[FieldImportStrategy] = None
    var inapplicable: Option[Boolean] = None
    var includeFrom: Option[String] = None
    var includeSummaryFunction: Option[SummaryFunction] = None
    var includeVia: Option[String] = None
    var initRequires: Option[VelocityExpression] = None
    var initRequiresAuthentication: Option[Boolean] = None
    var initRequiresRole: Option[String] = None
    var javaClass: Option[String] = None
    var javaCollectionClass: Option[String] = None
    var javaKeyClass: Option[String] = None
    var joinType: Option[JoinType] = None
    var length: Option[Int] = None
    var lenientXPath: Option[Boolean] = None
    var maxFileSize: Option[Int] = None
    var mimeType: Option[String] = None
    var multiple: Option[Boolean] = None
    var multipleStorage: Option[MultipleFieldStorage] = None
    var multipleStorageSeparator: Option[Boolean] = None
    var multipleValueSeparator: Option[Boolean] = None
    var name: Option[ID] = None
    var nativeName: Option[String] = None
    var nillable: Option[Boolean] = None
    var nullReplacementValue: Option[js.Any] = None
    var precision: Option[js.Any] = None
    var primaryKey: Option[Boolean] = None
    var propertiesOnly: Option[Boolean] = None
    var readOnlyEditorType: Option[FormItem] = None
    var relatedTableAlias: Option[String] = None
    var required: Option[Boolean] = None
    var rootValue: Option[js.Any] = None
    var sequenceName: Option[String] = None
    var showFileInline: Option[Boolean] = None
    var sortByField: Option[String] = None
    var sqlDateFormat: Option[String] = None
    var sqlFalseValue: Option[String] = None
    var sqlStorageStrategy: Option[String] = None
    var sqlTrueValue: Option[String] = None
    var storeMilliseconds: Option[Boolean] = None
    var storeWithHash: Option[HashAlgorithm] = None
    var stringInBrowser: Option[Boolean] = None
    var summaryFunction: Option[SummaryFunction] = None
    var summaryValueTitle: Option[String] = None
    var tableName: Option[String] = None
    var timeFormatter: Option[TimeDisplayFormat] = None
    var title: Option[String] = None
    var updateRequires: Option[VelocityExpression] = None
    var updateRequiresAuthentication: Option[Boolean] = None
    var updateRequiresRole: Option[String] = None
    var uploadFieldName: Option[String] = None
    var validators: Option[Array[Validator]] = None
    var validOperators: Option[Array[OperatorId]] = None
    var valueMap: Option[ValueMap] = None
    var valueMapEnum: Option[String] = None
    var valueWriteXPath: Option[XPathExpression] = None
    var valueXPath: Option[XPathExpression] = None
    var viewRequires: Option[VelocityExpression] = None
    var viewRequiresAuthentication: Option[Boolean] = None
    var viewRequiresRole: Option[String] = None
    var xmlAttribute: Option[Boolean] = None
}
