package com.simplesys.SmartClient.System.Types

import com.simplesys.System.Types.FormItemBaseType

object FormItemComponentType extends FormItemBaseType {
    type FormItemComponentType = Value
    val AutoFitTextAreaItem,
    BlurbItem,
    BooleanItem,
    ButtonItem,
    CancelItem,
    CanvasItem,
    CheckboxItem,
    ColorItem,
    ColorPickerItem,
    ComboBoxItem,
    CycleItem,
    DataPathItem,
    DateItem,
    DateRangeItem,
    DateTimeItem,
    DoubleItem,
    FileItem,
    FloatItem,
    FormItem,
    HeaderItem,
    HiddenItem,
    IntegerItem,
    IPickTreeItem,
    LinkItem,
    MiniDateRangeItem,
    MultiComboBoxItem,
    MultiFileItem,
    NativeCheckboxItem,
    PasswordItem,
    PickList,
    PickListMenu,
    PickTreeItem,
    PresetCriteriaItem,
    PresetDateRangeItem,
    RadioGroupItem,
    RelationItem,
    RelativeDateItem,
    ResetItem,
    RichTextItem,
    RowSpacerItem,
    ScrollingMenu,
    SectionItem,
    SelectItem,
    SelectOtherItem,
    SliderItem,
    SpacerItem,
    SpinnerItem,
    StaticTextItem,
    SubmitItem,
    TextAreaItem,
    TextItem,
    TimeItem,
    TimerItem,
    ToolbarItem,
    UploadItem,
    ComboboxItemWithButtons,
    FormItemWithButton,
    ComboboxItemWithClearButton,
    TextItemWithFormEdit,
    SkinBoxItem,
    ViewFileItem = Value
}
